name: metadata_fetch
description: A dart library for extracting metadata on web pages such as OpenGraph, Meta, Twitter Cards, and Structured Data (Json-LD)
version: 0.4.1
homepage: https://github.com/jg-l/metadata_fetch

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^1.0.0
  string_validator: ^0.3.0
  html: ^0.15.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
